export const PERSONAL_UPDATE = 'PERSONAL_UPDATE';
export const EDUCATION_UPDATE = 'EDUCATION_UPDATE';
export const PROFESSION_UPDATE='PROFESSION_UPDATE';
export const EXPERIENCES_UPDATE = 'EXPERIENCES_UPDATE';